title: Nicholas Clooney
url: https://blog.nicholas.clooney.io/

author:
  name: Nicholas Clooney
  email: not-gonna-tell-you@nicholas-clooney.simplelogin.com # 😉 You can still reach me.

theme:
  showSelectors: true
  previewResetDelay: 200
  transitionDuration: 0.5s
   # all options: linear, ease, ease-in, ease-out, ease-in-out
  transitionTimingFunction: ease-in-out
  defaultId: sun

headerLinks:
  - label: GitHub
    url: https://github.com/TheClooneyCollection/11ty-subspace-builder
  - label: Nicholas's Blog
    url: https://blog.nicholas.clooney.io/
  - label: Mastodon
    url: https://mastodon.social/@NicholasClooney
    rel: me


# tracking with umami
umami:
  source: https://analytics.clooney.ninja/script.js
  id: 49fa5de1-ee69-4faa-b73e-7fdf92e3c808

# giscus comments system
# get your config here: https://giscus.app/
giscus:
  repo: NicholasClooney/blog.clooney.io
  repoId: R_kgDOOtRluQ
  category: Announcements
  categoryId: DIC_kwDOOtRluc4CwANX
  mapping: og:title
